// vue-pokedex/src/components/PokemonList.vue
<script setup lang="ts">
	import PokemonCard from "./PokemonCard.vue";
	const props = defineProps<{
		pokemons: IndexedPokemon[];
	}>();
</script>

<template>
	<div class="pokemon-list">
		<PokemonCard
			v-for="pokemon in props.pokemons"
			:key="pokemon.index"
			:pokemon="pokemon"
		/>
	</div>
</template>

<style scoped>
	.pokemon-list {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
	}
</style>

// svelte-pokedex/src/lib/components/PokemonList.svelte
<script lang="ts">
	import PokemonCard from "./PokemonCard.svelte";
	export let pokemons: IndexedPokemon[];
</script>

<div class="pokemon-list">
	{#each pokemons as pokemon (pokemon.index)}
		<PokemonCard {pokemon} />
	{/each}
</div>

<style>
	.pokemon-list {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
	}
</style>
