// vue-pokedex/src/components/PokemonList.vue
<script setup lang="ts">
	import PokemonCard from "./PokemonCard.vue";
	const props = defineProps<{
		pokemons: IndexedPokemon[];
	}>();
</script>

<template>
	<div class="pokemon-list">
		<PokemonCard
			v-for="pokemon in props.pokemons"
			:key="pokemon.index"
			:pokemon="pokemon"
		/>
	</div>
</template>

<style scoped>
	.pokemon-list {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
	}
</style>

// react-pokedex/src/components/PokemonList.tsx
import { FunctionComponent } from "react";
import PokemonCard from "./PokemonCard";

interface PokemonListProps {
   pokemons: IndexedPokemon[];
}

const PokemonList: FunctionComponent<PokemonListProps> = ({ pokemons }) => {
   return (
      <div className="pokemon-list">
         {pokemons.map((pokemon) => (
            <PokemonCard key={pokemon.index} pokemon={pokemon} />)
         )}
      </div>
   );
}

export default PokemonList;
