// svelte-pokedex/src/lib/components/SearchBar.svelte
<script lang="ts">
	export let searchQuery: string;
</script>

<div class="search-bar">
	<input
		class="search-field"
		type="text"
		bind:value={searchQuery}
		placeholder="Search Pokemon..."
	/>
	<button class="search-clear" on:click={() => (searchQuery = "")}>
		Clear
	</button>
</div>

<style>
	.search-bar {
		display: flex;
		width: 100%;
	}

	.search-field {
		padding: 1rem;
		flex-grow: 1;
		font-size: large;
		border: none;
		border-bottom: 1px solid gray;
		outline: none;
	}

	.search-field:focus {
		border: none;
		border-bottom: 1px solid;
	}

	.search-clear {
		padding: 0 1rem;
		font-size: large;
		background-color: #f0f2f4;
		border: 1px solid #c3c3c5;
	}

	.search-clear:hover {
		background-color: #e0e1e4;
	}
</style>

// react-pokedex/src/components/SearchBar.tsx
import { Dispatch, FC, SetStateAction } from "react";

interface Props {
   searchQuery: string;
   setSearchQuery: Dispatch<SetStateAction<string>>;
}

const SearchBar: FC<Props> = ({ searchQuery, setSearchQuery }) => {
   return (
      <div className="search-bar">
         <input
            className="search-field"
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search Pokemon..."
         />
         <button className="search-clear" onClick={() => setSearchQuery("")}>
            Clear
         </button>
      </div>
   );
}

export default SearchBar;
