// react-pokedex/src/views/Pokemon.tsx
import { FunctionComponent } from "react";
import { useParams } from "react-router-dom";
import PokemonInfo from "../components/PokemonInfo";
import Stairs from "../components/Stairs";
import useFetchPokemon from "../hooks/useFetchPokemon";

interface PokemonProps {

}

const Pokemon: FunctionComponent<PokemonProps> = () => {
   let { id } = useParams();
   const { data, loading, error } = useFetchPokemon(`https://pokeapi.co/api/v2/pokemon/${id}`);

   return (
      <div className="pokemon-container">
         {loading && <Stairs></Stairs>}
         {error && <h2>Seems like there's an error: {error.message}</h2>}
         {data && <PokemonInfo pokemon={data} />}
      </div>
   );
}

export default Pokemon;

// svelte-pokedex/src/lib/views/Pokemon.svelte
<script lang="ts">
	import { useParams } from "svelte-navigator";
	import PokemonInfo from "../components/PokemonInfo.svelte";
	import Stairs from "../components/Stairs.svelte";
	import useFetchPokemon from "../hooks/useFetchPokemon";

	const params = useParams();
	const { data, loading, error } = useFetchPokemon(
		`https://pokeapi.co/api/v2/pokemon/${$params.id}`
	);
</script>

<div class="pokemon-container">
	{#if $loading}
		<Stairs />
	{:else if $error}
		<h2>Seems like there's an error: {$error.message}</h2>
	{:else}
		<PokemonInfo pokemon={$data} />
	{/if}
</div>

<style>
	.pokemon-container {
		display: flex;
		flex-flow: column;
		justify-content: center;
		align-items: center;
		background-color: #f0f2f4;
		padding: 1rem;
	}
</style>
