// svelte-pokedex/src/lib/views/Pokemon.svelte
<script lang="ts">
	import { useParams } from "svelte-navigator";
	import PokemonInfo from "../components/PokemonInfo.svelte";
	import Stairs from "../components/Stairs.svelte";
	import useFetchPokemon from "../hooks/useFetchPokemon";

	const params = useParams();
	const { data, loading, error } = useFetchPokemon(
		`https://pokeapi.co/api/v2/pokemon/${$params.id}`
	);
</script>

<div class="pokemon-container">
	{#if $loading}
		<Stairs />
	{:else if $error}
		<h2>Seems like there's an error: {$error.message}</h2>
	{:else}
		<PokemonInfo pokemon={$data} />
	{/if}
</div>

<style>
	.pokemon-container {
		display: flex;
		flex-flow: column;
		justify-content: center;
		align-items: center;
		background-color: #f0f2f4;
		padding: 1rem;
	}
</style>

// vue-pokedex/src/views/Pokemon.vue
<script setup lang="ts">
	import { useRoute } from "vue-router";
	import useFetchPokemon from "../hooks/useFetchPokemon";
	import Stairs from "../components/Stairs.vue";
	import PokemonInfo from "../components/PokemonInfo.vue";

	const route = useRoute();
	const { data, loading, error } = useFetchPokemon(
		`https://pokeapi.co/api/v2/pokemon/${route.params.id}`
	);
</script>

<template>
	<div class="pokemon-container">
		<Stairs v-if="loading" />
		<h2 v-else-if="error">Seems like there's an error: {$error.message}</h2>
		<PokemonInfo v-else-if="data" :pokemon="data" />
	</div>
</template>

<style scoped>
	.pokemon-container {
		display: flex;
		flex-flow: column;
		justify-content: center;
		align-items: center;
		background-color: #f0f2f4;
		padding: 1rem;
	}
</style>
